// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schemaref

// S3 pointer that crosses the wire in place of heavy bytes.
type ClaimCheck struct {
	// Bucket corresponds to the JSON schema field "bucket".
	Bucket string `json:"bucket" yaml:"bucket" mapstructure:"bucket"`

	// Key corresponds to the JSON schema field "key".
	Key string `json:"key" yaml:"key" mapstructure:"key"`
}

// Enters at ingestion and re-enters on zip/email fan-out.
type DocumentPipelineEvent struct {
	// ContentType corresponds to the JSON schema field "contentType".
	ContentType *string `json:"contentType,omitempty,omitzero" yaml:"contentType,omitempty" mapstructure:"contentType,omitempty"`

	// CorrelationID corresponds to the JSON schema field "correlationId".
	CorrelationID string `json:"correlationId" yaml:"correlationId" mapstructure:"correlationId"`

	// DocumentID corresponds to the JSON schema field "documentId".
	DocumentID string `json:"documentId" yaml:"documentId" mapstructure:"documentId"`

	// Filename corresponds to the JSON schema field "filename".
	Filename string `json:"filename" yaml:"filename" mapstructure:"filename"`

	// IdempotencyKey corresponds to the JSON schema field "idempotencyKey".
	IdempotencyKey string `json:"idempotencyKey" yaml:"idempotencyKey" mapstructure:"idempotencyKey"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// MessageID corresponds to the JSON schema field "messageId".
	MessageID string `json:"messageId" yaml:"messageId" mapstructure:"messageId"`

	// ParentDocumentID corresponds to the JSON schema field "parentDocumentId".
	ParentDocumentID DocumentPipelineEventParentDocumentID `json:"parentDocumentId,omitempty,omitzero" yaml:"parentDocumentId,omitempty" mapstructure:"parentDocumentId,omitempty"`

	// PipelineExecutionID corresponds to the JSON schema field "pipelineExecutionId".
	PipelineExecutionID string `json:"pipelineExecutionId" yaml:"pipelineExecutionId" mapstructure:"pipelineExecutionId"`

	// SchemaVersion corresponds to the JSON schema field "schemaVersion".
	SchemaVersion string `json:"schemaVersion" yaml:"schemaVersion" mapstructure:"schemaVersion"`

	// Source corresponds to the JSON schema field "source".
	Source ClaimCheck `json:"source" yaml:"source" mapstructure:"source"`

	// TaskToken corresponds to the JSON schema field "taskToken".
	TaskToken EnvelopeTaskToken `json:"taskToken,omitempty,omitzero" yaml:"taskToken,omitempty" mapstructure:"taskToken,omitempty"`

	// TenantID corresponds to the JSON schema field "tenantId".
	TenantID string `json:"tenantId" yaml:"tenantId" mapstructure:"tenantId"`

	// Traceparent corresponds to the JSON schema field "traceparent".
	Traceparent string `json:"traceparent" yaml:"traceparent" mapstructure:"traceparent"`

	// WorkspaceID corresponds to the JSON schema field "workspaceId".
	WorkspaceID string `json:"workspaceId" yaml:"workspaceId" mapstructure:"workspaceId"`
}

type DocumentPipelineEventParentDocumentID *string

// Spine present on every message of every family.
type Envelope struct {
	// CorrelationID corresponds to the JSON schema field "correlationId".
	CorrelationID string `json:"correlationId" yaml:"correlationId" mapstructure:"correlationId"`

	// DocumentID corresponds to the JSON schema field "documentId".
	DocumentID string `json:"documentId" yaml:"documentId" mapstructure:"documentId"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// MessageID corresponds to the JSON schema field "messageId".
	MessageID string `json:"messageId" yaml:"messageId" mapstructure:"messageId"`

	// PipelineExecutionID corresponds to the JSON schema field "pipelineExecutionId".
	PipelineExecutionID string `json:"pipelineExecutionId" yaml:"pipelineExecutionId" mapstructure:"pipelineExecutionId"`

	// SchemaVersion corresponds to the JSON schema field "schemaVersion".
	SchemaVersion string `json:"schemaVersion" yaml:"schemaVersion" mapstructure:"schemaVersion"`

	// Source corresponds to the JSON schema field "source".
	Source ClaimCheck `json:"source" yaml:"source" mapstructure:"source"`

	// TaskToken corresponds to the JSON schema field "taskToken".
	TaskToken EnvelopeTaskToken `json:"taskToken,omitempty,omitzero" yaml:"taskToken,omitempty" mapstructure:"taskToken,omitempty"`

	// TenantID corresponds to the JSON schema field "tenantId".
	TenantID string `json:"tenantId" yaml:"tenantId" mapstructure:"tenantId"`

	// Traceparent corresponds to the JSON schema field "traceparent".
	Traceparent string `json:"traceparent" yaml:"traceparent" mapstructure:"traceparent"`
}

type EnvelopeTaskToken *string

// Uniform error shape on non-GraphQL surfaces.
type ErrorEnvelope struct {
	// Code corresponds to the JSON schema field "code".
	Code string `json:"code" yaml:"code" mapstructure:"code"`

	// Detail corresponds to the JSON schema field "detail".
	Detail interface{} `json:"detail,omitempty,omitzero" yaml:"detail,omitempty" mapstructure:"detail,omitempty"`

	// Extensions corresponds to the JSON schema field "extensions".
	Extensions ErrorEnvelopeExtensions `json:"extensions,omitempty,omitzero" yaml:"extensions,omitempty" mapstructure:"extensions,omitempty"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message" yaml:"message" mapstructure:"message"`

	// Retryable corresponds to the JSON schema field "retryable".
	Retryable bool `json:"retryable" yaml:"retryable" mapstructure:"retryable"`
}

type ErrorEnvelopeExtensions map[string]interface{}

// Single source of truth for the document-uploader wire contract. Go/TS/Py flavors
// are generated from this; only the wire envelope crosses a queue.
type PipelineContractsSchemaJson map[string]interface{}

type StageName string

const StageNameClassify StageName = "classify"
const StageNameEmailExtraction StageName = "email-extraction"
const StageNameHtmlConvert StageName = "html-convert"
const StageNameImageTiff StageName = "image-tiff"
const StageNameMediaConvert StageName = "media-convert"
const StageNameOcr StageName = "ocr"
const StageNameOfficeConvert StageName = "office-convert"
const StageNameOutputAssembly StageName = "output-assembly"
const StageNamePdfProcessing StageName = "pdf-processing"
const StageNameSlipsheet StageName = "slipsheet"
const StageNameTiffCog StageName = "tiff-cog"
const StageNameZipExtraction StageName = "zip-extraction"

// What orchestration sends to a stage's queue.
type StageRequest struct {
	// CorrelationID corresponds to the JSON schema field "correlationId".
	CorrelationID string `json:"correlationId" yaml:"correlationId" mapstructure:"correlationId"`

	// DocumentID corresponds to the JSON schema field "documentId".
	DocumentID string `json:"documentId" yaml:"documentId" mapstructure:"documentId"`

	// IdempotencyKey corresponds to the JSON schema field "idempotencyKey".
	IdempotencyKey string `json:"idempotencyKey" yaml:"idempotencyKey" mapstructure:"idempotencyKey"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// MessageID corresponds to the JSON schema field "messageId".
	MessageID string `json:"messageId" yaml:"messageId" mapstructure:"messageId"`

	// Options corresponds to the JSON schema field "options".
	Options StageRequestOptions `json:"options,omitempty,omitzero" yaml:"options,omitempty" mapstructure:"options,omitempty"`

	// PipelineExecutionID corresponds to the JSON schema field "pipelineExecutionId".
	PipelineExecutionID string `json:"pipelineExecutionId" yaml:"pipelineExecutionId" mapstructure:"pipelineExecutionId"`

	// SchemaVersion corresponds to the JSON schema field "schemaVersion".
	SchemaVersion string `json:"schemaVersion" yaml:"schemaVersion" mapstructure:"schemaVersion"`

	// Source corresponds to the JSON schema field "source".
	Source ClaimCheck `json:"source" yaml:"source" mapstructure:"source"`

	// Stage corresponds to the JSON schema field "stage".
	Stage StageName `json:"stage" yaml:"stage" mapstructure:"stage"`

	// TaskToken corresponds to the JSON schema field "taskToken".
	TaskToken EnvelopeTaskToken `json:"taskToken,omitempty,omitzero" yaml:"taskToken,omitempty" mapstructure:"taskToken,omitempty"`

	// TenantID corresponds to the JSON schema field "tenantId".
	TenantID string `json:"tenantId" yaml:"tenantId" mapstructure:"tenantId"`

	// Traceparent corresponds to the JSON schema field "traceparent".
	Traceparent string `json:"traceparent" yaml:"traceparent" mapstructure:"traceparent"`
}

type StageRequestOptions map[string]interface{}

// What a stage emits to update-document-state.
type StageStatusUpdate struct {
	// CorrelationID corresponds to the JSON schema field "correlationId".
	CorrelationID string `json:"correlationId" yaml:"correlationId" mapstructure:"correlationId"`

	// DocumentID corresponds to the JSON schema field "documentId".
	DocumentID string `json:"documentId" yaml:"documentId" mapstructure:"documentId"`

	// Error corresponds to the JSON schema field "error".
	Error *ErrorEnvelope `json:"error,omitempty,omitzero" yaml:"error,omitempty" mapstructure:"error,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// MessageID corresponds to the JSON schema field "messageId".
	MessageID string `json:"messageId" yaml:"messageId" mapstructure:"messageId"`

	// Outputs corresponds to the JSON schema field "outputs".
	Outputs []ClaimCheck `json:"outputs,omitempty,omitzero" yaml:"outputs,omitempty" mapstructure:"outputs,omitempty"`

	// PipelineExecutionID corresponds to the JSON schema field "pipelineExecutionId".
	PipelineExecutionID string `json:"pipelineExecutionId" yaml:"pipelineExecutionId" mapstructure:"pipelineExecutionId"`

	// SchemaVersion corresponds to the JSON schema field "schemaVersion".
	SchemaVersion string `json:"schemaVersion" yaml:"schemaVersion" mapstructure:"schemaVersion"`

	// Source corresponds to the JSON schema field "source".
	Source ClaimCheck `json:"source" yaml:"source" mapstructure:"source"`

	// Stage corresponds to the JSON schema field "stage".
	Stage StageName `json:"stage" yaml:"stage" mapstructure:"stage"`

	// Status corresponds to the JSON schema field "status".
	Status StatusValue `json:"status" yaml:"status" mapstructure:"status"`

	// TaskToken corresponds to the JSON schema field "taskToken".
	TaskToken EnvelopeTaskToken `json:"taskToken,omitempty,omitzero" yaml:"taskToken,omitempty" mapstructure:"taskToken,omitempty"`

	// TenantID corresponds to the JSON schema field "tenantId".
	TenantID string `json:"tenantId" yaml:"tenantId" mapstructure:"tenantId"`

	// Traceparent corresponds to the JSON schema field "traceparent".
	Traceparent string `json:"traceparent" yaml:"traceparent" mapstructure:"traceparent"`
}

type StatusValue string

const StatusValueFAILED StatusValue = "FAILED"
const StatusValuePARTIALFAILED StatusValue = "PARTIAL_FAILED"
const StatusValueSUCCESS StatusValue = "SUCCESS"
