{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "convert-worker.serviceAccountName" . }}
  namespace: {{ include "convert-worker.namespace" . }}
  labels:
    {{- include "convert-worker.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}
  {{- end }}
{{- end -}}
