package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strings"
	"time"

	contracts "github.com/opus2/docuploader/libs/pipeline-contracts/go"
	"github.com/opus2/docuploader/units/ingestion-service/ingestion-subgraph/graph/model"
	"github.com/opus2/docuploader/units/ingestion-service/ingestion-subgraph/internal/app"
)

// CreateWorkspace is the resolver for the createWorkspace field.
func (r *mutationResolver) CreateWorkspace(ctx context.Context, input model.CreateWorkspaceInput) (*model.Workspace, error) {
	w, err := r.Store.CreateWorkspace(ctx, input.RetentionDays)
	if err != nil {
		return nil, err
	}
	m := toWorkspace(w)
	return &m, nil
}

// CreateDocument is the resolver for the createDocument field.
func (r *mutationResolver) CreateDocument(ctx context.Context, input model.CreateDocumentInput) (*model.CreateDocumentResult, error) {
	contentType := ""
	if input.ContentType != nil {
		contentType = *input.ContentType
	}
	d, err := r.Store.CreateDocument(ctx, input.WorkspaceID, input.Filename, contentType)
	if err != nil {
		return nil, err
	}
	url, _, err := r.Uploader.Presign(ctx, r.Tenant, d.ID, d.Filename)
	if err != nil {
		return nil, err
	}
	md := toDocument(d)
	return &model.CreateDocumentResult{Document: &md, UploadURL: url}, nil
}

// ClassifyDocument is the resolver for the classifyDocument field — claim-check
// + dispatch a StageRequest into the pipeline, then mark the doc PROCESSING.
func (r *mutationResolver) ClassifyDocument(ctx context.Context, documentID string) (*model.Document, error) {
	dp, err := r.Store.Document(ctx, documentID)
	if err != nil {
		return nil, err
	}
	if dp == nil {
		return nil, fmt.Errorf("document %s not found", documentID)
	}
	// Claim-check pointer (POC re-derives the key; real flow stores it at create).
	_, source, err := r.Uploader.Presign(ctx, r.Tenant, dp.ID, dp.Filename)
	if err != nil {
		return nil, err
	}
	if err := r.Dispatcher.Dispatch(ctx, contracts.StageClassify, r.Tenant, *dp, source, app.NewTraceparent()); err != nil {
		return nil, err
	}
	stage := string(contracts.StageClassify)
	d, err := r.Store.SetStatus(ctx, documentID, "PROCESSING", &stage)
	if err != nil {
		return nil, err
	}
	r.Bus.Publish(d) // notify any documentStatusChanged subscribers
	m := toDocument(d)
	return &m, nil
}

// Classify is the resolver for the classify field. Synchronous: looks up the
// uploaded document's claim-check and calls the classification service's
// /classify endpoint, returning the result inline.
func (r *mutationResolver) Classify(ctx context.Context, documentID string) (*model.ClassificationResult, error) {
	dp, err := r.Store.Document(ctx, documentID)
	if err != nil {
		return nil, err
	}
	if dp == nil {
		return nil, fmt.Errorf("document %s not found", documentID)
	}
	// Claim-check pointer (POC re-derives the key; real flow stores it at create).
	_, source, err := r.Uploader.Presign(ctx, r.Tenant, dp.ID, dp.Filename)
	if err != nil {
		return nil, err
	}
	res, err := r.Classifier.Classify(ctx, dp.WorkspaceID, dp.ID, source, extensionOf(dp.Filename), dp.ContentType)
	if err != nil {
		return nil, err
	}
	m := toClassificationResult(res)
	return &m, nil
}

// SaveWorkspaceConfig is the resolver for the saveWorkspaceConfig field.
func (r *mutationResolver) SaveWorkspaceConfig(ctx context.Context, input model.WorkspaceConfigInput) (*model.WorkspaceConfig, error) {
	saved, err := r.WorkspaceConfigStore.SaveConfig(ctx, workspaceConfigFromInput(input))
	if err != nil {
		return nil, err
	}
	m := toWorkspaceConfigModel(saved)
	return &m, nil
}

// ReapStuckConverts is the resolver for the reapStuckConverts field. Force-fails
// convert rows stuck in `converting` past the watchdog cutoff (the UI's old
// /api/admin/convert-watchdog; the shared-secret gate stays on the UI route).
func (r *mutationResolver) ReapStuckConverts(ctx context.Context) (*model.ReapResult, error) {
	res, err := r.RunStore.ReapStuckConverts(ctx, watchdogStuckAfter(), watchdogMaxRows())
	if err != nil {
		return nil, err
	}
	reaped := make([]model.ReapedRun, 0, len(res.Reaped))
	for _, x := range res.Reaped {
		reaped = append(reaped, model.ReapedRun{
			WorkspaceID:      x.WorkspaceID,
			RunID:            x.RunID,
			ConvertStartedAt: x.ConvertStartedAt,
		})
	}
	return &model.ReapResult{
		Ok:           true,
		ScannedCount: res.ScannedCount,
		ReapedCount:  res.ReapedCount,
		CutoffIso:    res.CutoffISO,
		StuckAfterMs: int(res.StuckAfterMs),
		DurationMs:   int(res.DurationMs),
		Reaped:       reaped,
	}, nil
}

// Workspaces is the resolver for the workspaces field.
func (r *queryResolver) Workspaces(ctx context.Context) ([]model.Workspace, error) {
	ws, err := r.Store.Workspaces(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.Workspace, 0, len(ws))
	for _, w := range ws {
		out = append(out, toWorkspace(w))
	}
	return out, nil
}

// Documents is the resolver for the documents field.
func (r *queryResolver) Documents(ctx context.Context, workspaceID string) ([]model.Document, error) {
	ds, err := r.Store.Documents(ctx, workspaceID)
	if err != nil {
		return nil, err
	}
	out := make([]model.Document, 0, len(ds))
	for _, d := range ds {
		out = append(out, toDocument(d))
	}
	return out, nil
}

// Document is the resolver for the document field.
func (r *queryResolver) Document(ctx context.Context, id string) (*model.Document, error) {
	dp, err := r.Store.Document(ctx, id)
	if err != nil || dp == nil {
		return nil, err
	}
	m := toDocument(*dp)
	return &m, nil
}

// Stats is the resolver for the stats field.
func (r *queryResolver) Stats(ctx context.Context) (*model.Stats, error) {
	w, d, err := r.Store.Stats(ctx)
	if err != nil {
		return nil, err
	}
	return &model.Stats{Workspaces: w, Documents: d}, nil
}

// WorkspaceConfig is the resolver for the workspaceConfig field.
func (r *queryResolver) WorkspaceConfig(ctx context.Context, workspaceID string) (*model.WorkspaceConfig, error) {
	c, err := r.WorkspaceConfigStore.GetConfig(ctx, workspaceID)
	if err != nil || c == nil {
		return nil, err
	}
	m := toWorkspaceConfigModel(*c)
	return &m, nil
}

// WorkspaceConfigs is the resolver for the workspaceConfigs field.
func (r *queryResolver) WorkspaceConfigs(ctx context.Context) ([]model.WorkspaceConfig, error) {
	cs, err := r.WorkspaceConfigStore.ListConfigs(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.WorkspaceConfig, 0, len(cs))
	for _, c := range cs {
		out = append(out, toWorkspaceConfigModel(c))
	}
	return out, nil
}

// DocumentRun is the resolver for the documentRun field. Mirrors the UI's old
// runs/[documentId] route: the content-hash DDB row + S3 object metadata +
// short-lived browser-reachable presigned downloads. Lookup failures degrade to
// nil fields (the UI swallowed them with .catch(()=>null)).
func (r *queryResolver) DocumentRun(ctx context.Context, workspaceID string, documentID string, contentHash *string, objectKey *string, runID *string) (*model.DocumentRun, error) {
	out := &model.DocumentRun{
		DocumentID:  documentID,
		WorkspaceID: workspaceID,
		Bucket:      r.Target.Bucket,
		Table:       r.Target.ContentHashTable,
	}

	if contentHash != nil && *contentHash != "" {
		if row, err := r.RunStore.ContentHashRow(ctx, workspaceID, *contentHash); err == nil {
			out.DdbRow = row
		}
	}

	var convertRow map[string]any
	if runID != nil && *runID != "" {
		if row, err := r.RunStore.ConvertRow(ctx, workspaceID, *runID); err == nil {
			convertRow = row
			out.Convert = row
		}
	}

	if objectKey != nil && *objectKey != "" {
		if meta, err := r.ObjectStore.Head(ctx, r.Target.Bucket, *objectKey); err == nil {
			out.S3Object = toS3ObjectModel(meta)
		}
		// Defence-in-depth: only sign keys under the UI's own `ui/` prefix.
		if strings.HasPrefix(*objectKey, "ui/") {
			filename := lastSegment(*objectKey, "download")
			if url, err := r.ObjectStore.PresignDownload(ctx, r.Target.Bucket, *objectKey,
				fmt.Sprintf(`attachment; filename="%s"`, filename), ""); err == nil {
				out.DownloadURL = &url
			}
		}
	}

	// Presigned GET for the CONVERTED PDF once the worker has finished — only
	// keys under our own `converted/` prefix, same bucket.
	if convertRow != nil {
		if status, _ := convertRow["convertStatus"].(string); status == "done" {
			convertedKey, _ := convertRow["convertS3Key"].(string)
			convertedBucket, _ := convertRow["convertS3Bucket"].(string)
			if convertedKey != "" && strings.HasPrefix(convertedKey, "converted/") && convertedBucket == r.Target.Bucket {
				pdf := lastSegment(convertedKey, "document.pdf")
				if url, err := r.ObjectStore.PresignDownload(ctx, convertedBucket, convertedKey,
					fmt.Sprintf(`attachment; filename="%s"`, pdf), "application/pdf"); err == nil {
					out.ConvertedDownloadURL = &url
				}
			}
		}
	}

	return out, nil
}

// ClassificationStats is the resolver for the classificationStats field — the
// dashboard KPI tiles + recent feed, aggregated from the classifications table
// (the UI's old /api/stats, now durable instead of in-process counters).
func (r *queryResolver) ClassificationStats(ctx context.Context, workspaceID string) (*model.ClassificationStats, error) {
	s, err := r.RunStore.Stats(ctx, workspaceID)
	if err != nil {
		return nil, err
	}
	return toClassificationStatsModel(s), nil
}

// ConvertProgress is the resolver for the convertProgress field. Resolves the
// office-convert requestId off the classifications row, then forwards to the
// office-convert progress endpoint (the UI's old runs/[documentId]/progress).
func (r *queryResolver) ConvertProgress(ctx context.Context, workspaceID string, runID string) (*model.ConvertProgress, error) {
	var status, requestID *string
	if row, err := r.RunStore.ConvertRow(ctx, workspaceID, runID); err == nil && row != nil {
		if v, ok := row["convertStatus"].(string); ok {
			status = &v
		}
		if v, ok := row["convertRequestId"].(string); ok {
			requestID = &v
		}
	}

	// No live progress to fetch when the worker hasn't started (queued) or the
	// row is already terminal — return what we know.
	if requestID == nil || status == nil || *status != "converting" {
		reason := "no_request_id_yet"
		if requestID != nil {
			reason = "non_converting_status"
		}
		return &model.ConvertProgress{ConvertStatus: status, RequestID: requestID, Reason: &reason}, nil
	}

	progress, err := r.Resolver.ConvertProgress.Progress(ctx, *requestID)
	if err != nil {
		reason := err.Error()
		return &model.ConvertProgress{ConvertStatus: status, RequestID: requestID, Reason: &reason}, nil
	}
	return &model.ConvertProgress{ConvertStatus: status, RequestID: requestID, Progress: progress}, nil
}

// EmailExtraction is the resolver for the emailExtraction field — the parsed
// email-extraction payload persisted during classify (null if none). Replaces
// the UI's process-local in-memory cache with a durable DDB read.
func (r *queryResolver) EmailExtraction(ctx context.Context, documentID string) (*model.EmailExtraction, error) {
	payload, err := r.EmailStore.Get(ctx, documentID)
	if err != nil {
		return nil, err
	}
	if payload == nil {
		return nil, nil
	}
	return &model.EmailExtraction{DocumentID: documentID, Extraction: payload}, nil
}

// BackendTarget is the resolver for the backendTarget field — the operator-
// facing "what AWS surface is the router pointed at?" view (config resolved at
// wiring time).
func (r *queryResolver) BackendTarget(ctx context.Context) (*model.BackendTarget, error) {
	t := r.Target
	return &model.BackendTarget{
		Endpoint:             t.Endpoint,
		Region:               t.Region,
		Bucket:               t.Bucket,
		ContentHashTable:     t.ContentHashTable,
		WorkspaceConfigTable: t.WorkspaceConfigTable,
		Backend:              t.Backend,
	}, nil
}

// RouterHealth is the resolver for the routerHealth field — DynamoDB
// connectivity probe (the UI's old /api/health; the UI route maps ready:false
// onto an HTTP 503).
func (r *queryResolver) RouterHealth(ctx context.Context) (*model.RouterHealth, error) {
	start := time.Now()
	tables, err := r.Health.ListTables(ctx)
	latency := int(time.Since(start).Milliseconds())
	if err != nil {
		return &model.RouterHealth{Ready: false, Endpoint: r.Target.Endpoint, Tables: []string{}, LatencyMs: latency}, nil
	}
	return &model.RouterHealth{Ready: true, Endpoint: r.Target.Endpoint, Tables: tables, LatencyMs: latency}, nil
}

// DocumentStatusChanged is the resolver for the documentStatusChanged field.
func (r *subscriptionResolver) DocumentStatusChanged(ctx context.Context, documentID string) (<-chan *model.Document, error) {
	in := r.Bus.Subscribe(ctx, documentID)
	out := make(chan *model.Document, 1)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case d, ok := <-in:
				if !ok {
					return
				}
				m := toDocument(d)
				select {
				case out <- &m:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
