package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	contracts "github.com/opus2/docuploader/libs/pipeline-contracts/go"
	"github.com/opus2/docuploader/units/ingestion-service/ingestion-subgraph/graph/model"
	"github.com/opus2/docuploader/units/ingestion-service/ingestion-subgraph/internal/app"
)

// CreateWorkspace is the resolver for the createWorkspace field.
func (r *mutationResolver) CreateWorkspace(ctx context.Context, input model.CreateWorkspaceInput) (*model.Workspace, error) {
	w, err := r.Store.CreateWorkspace(ctx, input.RetentionDays)
	if err != nil {
		return nil, err
	}
	m := toWorkspace(w)
	return &m, nil
}

// CreateDocument is the resolver for the createDocument field.
func (r *mutationResolver) CreateDocument(ctx context.Context, input model.CreateDocumentInput) (*model.CreateDocumentResult, error) {
	contentType := ""
	if input.ContentType != nil {
		contentType = *input.ContentType
	}
	d, err := r.Store.CreateDocument(ctx, input.WorkspaceID, input.Filename, contentType)
	if err != nil {
		return nil, err
	}
	url, _, err := r.Uploader.Presign(ctx, r.Tenant, d.ID, d.Filename)
	if err != nil {
		return nil, err
	}
	md := toDocument(d)
	return &model.CreateDocumentResult{Document: &md, UploadURL: url}, nil
}

// ClassifyDocument is the resolver for the classifyDocument field — claim-check
// + dispatch a StageRequest into the pipeline, then mark the doc PROCESSING.
func (r *mutationResolver) ClassifyDocument(ctx context.Context, documentID string) (*model.Document, error) {
	dp, err := r.Store.Document(ctx, documentID)
	if err != nil {
		return nil, err
	}
	if dp == nil {
		return nil, fmt.Errorf("document %s not found", documentID)
	}
	// Claim-check pointer (POC re-derives the key; real flow stores it at create).
	_, source, err := r.Uploader.Presign(ctx, r.Tenant, dp.ID, dp.Filename)
	if err != nil {
		return nil, err
	}
	if err := r.Dispatcher.Dispatch(ctx, contracts.StageClassify, r.Tenant, *dp, source, app.NewTraceparent()); err != nil {
		return nil, err
	}
	stage := string(contracts.StageClassify)
	d, err := r.Store.SetStatus(ctx, documentID, "PROCESSING", &stage)
	if err != nil {
		return nil, err
	}
	r.Bus.Publish(d) // notify any documentStatusChanged subscribers
	m := toDocument(d)
	return &m, nil
}

// Classify is the resolver for the classify field. Synchronous: looks up the
// uploaded document's claim-check and calls the classification service's
// /classify endpoint, returning the result inline.
func (r *mutationResolver) Classify(ctx context.Context, documentID string) (*model.ClassificationResult, error) {
	dp, err := r.Store.Document(ctx, documentID)
	if err != nil {
		return nil, err
	}
	if dp == nil {
		return nil, fmt.Errorf("document %s not found", documentID)
	}
	// Claim-check pointer (POC re-derives the key; real flow stores it at create).
	_, source, err := r.Uploader.Presign(ctx, r.Tenant, dp.ID, dp.Filename)
	if err != nil {
		return nil, err
	}
	res, err := r.Classifier.Classify(ctx, dp.WorkspaceID, dp.ID, source, extensionOf(dp.Filename), dp.ContentType)
	if err != nil {
		return nil, err
	}
	m := toClassificationResult(res)
	return &m, nil
}

// Workspaces is the resolver for the workspaces field.
func (r *queryResolver) Workspaces(ctx context.Context) ([]model.Workspace, error) {
	ws, err := r.Store.Workspaces(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.Workspace, 0, len(ws))
	for _, w := range ws {
		out = append(out, toWorkspace(w))
	}
	return out, nil
}

// Documents is the resolver for the documents field.
func (r *queryResolver) Documents(ctx context.Context, workspaceID string) ([]model.Document, error) {
	ds, err := r.Store.Documents(ctx, workspaceID)
	if err != nil {
		return nil, err
	}
	out := make([]model.Document, 0, len(ds))
	for _, d := range ds {
		out = append(out, toDocument(d))
	}
	return out, nil
}

// Document is the resolver for the document field.
func (r *queryResolver) Document(ctx context.Context, id string) (*model.Document, error) {
	dp, err := r.Store.Document(ctx, id)
	if err != nil || dp == nil {
		return nil, err
	}
	m := toDocument(*dp)
	return &m, nil
}

// Stats is the resolver for the stats field.
func (r *queryResolver) Stats(ctx context.Context) (*model.Stats, error) {
	w, d, err := r.Store.Stats(ctx)
	if err != nil {
		return nil, err
	}
	return &model.Stats{Workspaces: w, Documents: d}, nil
}

// DocumentStatusChanged is the resolver for the documentStatusChanged field.
func (r *subscriptionResolver) DocumentStatusChanged(ctx context.Context, documentID string) (<-chan *model.Document, error) {
	in := r.Bus.Subscribe(ctx, documentID)
	out := make(chan *model.Document, 1)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case d, ok := <-in:
				if !ok {
					return
				}
				m := toDocument(d)
				select {
				case out <- &m:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
