// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Synchronous classification result (from the classification service /classify).
type ClassificationResult struct {
	DocumentID        string  `json:"documentId"`
	WorkspaceID       string  `json:"workspaceId"`
	Format            string  `json:"format"`
	Category          string  `json:"category"`
	SubCategory       *string `json:"subCategory,omitempty"`
	ConfidenceScore   float64 `json:"confidenceScore"`
	DetectionTier     string  `json:"detectionTier"`
	IsForcedSlipsheet bool    `json:"isForcedSlipsheet"`
	ContentHash       string  `json:"contentHash"`
	IsDuplicate       bool    `json:"isDuplicate"`
	PolicyVersion     string  `json:"policyVersion"`
}

type CreateDocumentInput struct {
	WorkspaceID string  `json:"workspaceId"`
	Filename    string  `json:"filename"`
	ContentType *string `json:"contentType,omitempty"`
}

type CreateDocumentResult struct {
	Document *Document `json:"document"`
	// Presigned PUT URL — client uploads bytes directly to S3 (claim-check).
	UploadURL string `json:"uploadUrl"`
}

type CreateWorkspaceInput struct {
	RetentionDays *int `json:"retentionDays,omitempty"`
}

type Document struct {
	ID            string  `json:"id"`
	WorkspaceID   string  `json:"workspaceId"`
	Filename      string  `json:"filename"`
	ContentType   string  `json:"contentType"`
	Status        string  `json:"status"`
	PipelineStage *string `json:"pipelineStage,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Stats struct {
	Workspaces int `json:"workspaces"`
	Documents  int `json:"documents"`
}

type Subscription struct {
}

type Workspace struct {
	ID            string `json:"id"`
	Status        string `json:"status"`
	RetentionDays *int   `json:"retentionDays,omitempty"`
}
